import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const posContext = readFileSync(new URL('../dashboard/src/pos/lib/pos-context.tsx', import.meta.url), 'utf8')
const posLogin = readFileSync(new URL('../dashboard/src/pos/pages/pos-login.tsx', import.meta.url), 'utf8')
const salePage = readFileSync(new URL('../dashboard/src/pos/pages/sale.tsx', import.meta.url), 'utf8')
const lineActionModal = readFileSync(new URL('../dashboard/src/pos/components/line-action-modal.tsx', import.meta.url), 'utf8')
const receiptPreview = readFileSync(new URL('../dashboard/src/pos/components/receipt-preview.tsx', import.meta.url), 'utf8')
const productsPage = readFileSync(new URL('../dashboard/src/pages/products.tsx', import.meta.url), 'utf8')
const productsHook = readFileSync(new URL('../dashboard/src/hooks/use-products.ts', import.meta.url), 'utf8')
const skumsConnectorHook = readFileSync(new URL('../dashboard/src/hooks/use-skums-connector.ts', import.meta.url), 'utf8')
const dashboardPage = readFileSync(new URL('../dashboard/src/pages/dashboard.tsx', import.meta.url), 'utf8')
const loginPage = readFileSync(new URL('../dashboard/src/pages/auth/login.tsx', import.meta.url), 'utf8')
const posShell = readFileSync(new URL('../dashboard/src/pos/pos-shell.tsx', import.meta.url), 'utf8')
const posMockData = readFileSync(new URL('../dashboard/src/pos/data/mock.ts', import.meta.url), 'utf8')
const reportsPage = readFileSync(new URL('../dashboard/src/pos/pages/reports.tsx', import.meta.url), 'utf8')
const transfersPage = readFileSync(new URL('../dashboard/src/pos/pages/transfers.tsx', import.meta.url), 'utf8')
const returnsPage = readFileSync(new URL('../dashboard/src/pos/pages/returns.tsx', import.meta.url), 'utf8')
const stockPage = readFileSync(new URL('../dashboard/src/pos/pages/stock.tsx', import.meta.url), 'utf8')
const stockMovement = readFileSync(new URL('../dashboard/src/pos/lib/stock-movement.ts', import.meta.url), 'utf8')
const paymentModal = readFileSync(new URL('../dashboard/src/pos/components/payment-modal.tsx', import.meta.url), 'utf8')
const customerModal = readFileSync(new URL('../dashboard/src/pos/components/customer-modal.tsx', import.meta.url), 'utf8')
const skumsSaleAdapter = readFileSync(new URL('../dashboard/src/pos/lib/skums-sale-adapter.ts', import.meta.url), 'utf8')
const posOutbox = readFileSync(new URL('../dashboard/src/pos/lib/pos-outbox.ts', import.meta.url), 'utf8')
const customersHook = readFileSync(new URL('../dashboard/src/hooks/use-customers.ts', import.meta.url), 'utf8')
const skumsClient = readFileSync(new URL('../dashboard/src/pos/lib/skums-client.ts', import.meta.url), 'utf8')
const inventoryEventsMigration = readFileSync(new URL('../supabase/migrations/00005_create_pos_inventory_events.sql', import.meta.url), 'utf8')
const customerBirthdayMigration = readFileSync(new URL('../supabase/migrations/00006_add_customer_birthday.sql', import.meta.url), 'utf8')

test('POS start screen exposes demo and live mode choices', () => {
  assert.match(posContext, /export type PosMode = 'demo' \| 'live'/)
  assert.match(posContext, /localStorage\.getItem\('pos_mode'\)/)
  assert.match(posLogin, /Demo mode/)
  assert.match(posLogin, /Live mode/)
  assert.match(posLogin, /useSearchParams/)
  assert.match(posLogin, /requestedMode === 'demo' \|\| requestedMode === 'live'/)
  assert.match(posLogin, /Connected demo account/)
  assert.match(posLogin, /signInWithGoogle\('\/pos\?mode=demo'\)/)
  assert.match(posLogin, /signInWithGoogle\('\/pos'\)/)
  assert.match(posLogin, /Open Register/)
  assert.match(posLogin, /\/products\?new=1/)
  assert.match(posLogin, /\/products\?import=skums/)
  assert.match(posShell, /Account demo/)
  assert.match(posShell, /mobileNavOpen/)
  assert.match(posShell, /aria-label="Open POS menu"/)
  assert.match(posShell, /aria-label="POS menu"/)
  assert.match(posShell, /hidden w-16 shrink-0 flex-col items-center gap-1 border-r bg-card py-3 md:flex/)
  assert.match(posShell, /hidden text-center leading-tight lg:inline/)
  assert.match(loginPage, /\/pos\?mode=demo/)
  assert.match(dashboardPage, /Open POS Register/)
  assert.match(dashboardPage, /posRegisterPath = '\/pos\?mode=live'/)
})

test('POS PIN entry lets users recover from a wrong code with backspace', () => {
  assert.match(posLogin, /Incorrect PIN, try again/)
  assert.match(posLogin, /Incorrect or locked passcode/)
  assert.match(posLogin, /onBackspace=\{\(\) => \{\s*setError\(false\)\s*setPin\(\(p\) => p\.slice\(0, -1\)\)\s*\}\}/s)
})

test('Live sale mode loads POS database products before SKUMS fallback', () => {
  assert.match(salePage, /mode === 'demo'/)
  assert.match(salePage, /\.from\('products'\)/)
  assert.match(salePage, /setCatalogSource\('live'\)/)
  assert.match(salePage, /listSkumsPosCatalog\(\{ limit: 250 \}, skumsConnector\)/)
  assert.match(salePage, /const liveProducts = \(\(data \|\| \[\]\) as DbProduct\[\]\)\.map\(toLiveProduct\)/)
  assert.match(salePage, /const skumsProducts = res\.data\.map\(toPosProduct\)/)
  assert.doesNotMatch(salePage, /liveProducts = [^\n]+\.filter\(\(p\) => p\.price > 0\)/)
  assert.doesNotMatch(salePage, /skumsProducts = [^\n]+\.filter\(\(p\) => p\.price > 0\)/)
  assert.match(salePage, /pos_catalog_updated/)
  assert.match(salePage, /pos-catalog-updated/)
  assert.match(salePage, /No live products yet\. Create products manually or add a SKUMS connector\./)
  assert.match(salePage, /resolveSkumsPosScan/)
  assert.match(salePage, /Unified product entry/)
  assert.match(salePage, /aria-label="Product barcode, QR, or SKU"/)
  assert.match(salePage, /placeholder="Barcode \/ QR \/ SKU"/)
  assert.match(salePage, /type="submit"/)
  assert.match(salePage, /submitProductEntry/)
  assert.match(salePage, /productEntryRef/)
  assert.match(salePage, /CameraScanStatus/)
  assert.match(salePage, /CAMERA_BARCODE_FORMATS/)
  assert.match(salePage, /BarcodeDetector/)
  assert.match(salePage, /BrowserQRCodeReader/)
  assert.match(salePage, /BrowserMultiFormatOneDReader/)
  assert.match(salePage, /compatible scanner fallback/)
  assert.match(salePage, /navigator\.mediaDevices\?\.getUserMedia/)
  assert.match(salePage, /Open camera scanner/)
  assert.match(salePage, /Desktop webcam scanner/)
  assert.match(salePage, /Camera requires HTTPS or localhost/)
  assert.match(salePage, /await handleScanSubmit\(value\)/)
  assert.match(salePage, /CAMERA_RESCAN_COOLDOWN_MS/)
  assert.match(salePage, /CAMERA_SAME_CODE_DEBOUNCE_MS/)
  assert.match(salePage, /first recognized barcode or QR is added automatically/)
  assert.match(salePage, /Keep scanning for the next item/)
  assert.match(salePage, /scheduleRescan/)
  assert.doesNotMatch(salePage, /Use input/)
  assert.ok(salePage.indexOf('className="flex shrink-0 flex-col gap-2 border-b bg-card p-3 md:flex-row md:items-center"') < salePage.indexOf('<FranMemberStrip'))
  assert.match(salePage, /No local product matched this product code\./)
  assert.match(salePage, /Continue with product entry\./)
  assert.doesNotMatch(salePage, /search product/)
  assert.match(salePage, /match_status === 'ambiguous'/)
  assert.match(salePage, /No SKUMS match found\. Back office will review the scan\./)
})

test('POS sale catalogue can switch between grid and list views', () => {
  assert.match(salePage, /type CatalogViewMode = 'grid' \| 'list'/)
  assert.match(salePage, /localStorage\.getItem\('pos_catalog_view'\)/)
  assert.match(salePage, /aria-label="Grid view"/)
  assert.match(salePage, /aria-label="List view"/)
  assert.match(salePage, /mobileCatalogOpen/)
  assert.match(salePage, /Product catalog/)
  assert.match(salePage, /Browse only when a product cannot scan\./)
  assert.match(salePage, /className="gap-2 md:hidden"/)
  assert.match(salePage, /hidden min-h-0 min-w-0 flex-col md:flex md:flex-1/)
  assert.match(salePage, /flex min-h-0 flex-1 overflow-hidden md:flex-row/)
  assert.match(salePage, /flex min-h-0 w-full flex-1 flex-col bg-card md:w-\[380px\]/)
  assert.doesNotMatch(salePage, /min-h-\[520px\]/)
  assert.doesNotMatch(salePage, /min-h-\[460px\]/)
  assert.match(salePage, /function ProductListRow/)
})

test('POS sale page removes void and supports saved baskets for near-checkout customers', () => {
  assert.doesNotMatch(salePage, />\s*Void\s*</)
  assert.doesNotMatch(salePage, /requestVoid/)
  assert.match(posContext, /export interface SavedBasket/)
  assert.match(posContext, /savedBasketStorageKey = 'pos_saved_baskets'/)
  assert.match(posContext, /saveBasket: \(label\?: string\) => SavedBasket \| null/)
  assert.match(posContext, /resumeSavedBasket: \(id: string\) => void/)
  assert.match(posContext, /removeSavedBasket: \(id: string\) => void/)
  assert.match(posContext, /storageMode: 'local' \| 'server_pending'/)
  assert.match(posContext, /savedBasketStoreForMode/)
  assert.match(salePage, /Saved baskets/)
  assert.match(salePage, /Save basket/)
  assert.match(salePage, /Optional basket name/)
  assert.match(salePage, /resumeSavedBasket\(basket\.id\)/)
})

test('POS sale page supports manager-authorized item and cart price overrides', () => {
  assert.match(posContext, /export interface CartPriceOverride/)
  assert.match(posContext, /cartPriceOverride: CartPriceOverride \| null/)
  assert.match(posContext, /overrideLinePrice: \(lineId: string, newPrice: number, reason: string\) => void/)
  assert.match(posContext, /overrideCartTotal: \(newTotal: number, reason: string\) => void/)
  assert.match(posContext, /cartAdjustment/)
  assert.match(posContext, /setCartPriceOverride\(null\)/)
  assert.match(lineActionModal, /onApplyOverride\(line\.lineId, v, overrideReason\)/)
  assert.match(salePage, /Override total/)
  assert.match(salePage, /CartOverrideModal/)
  assert.match(salePage, /Authorise cart total override/)
  assert.match(salePage, /run: \(\) => overrideCartTotal\(targetTotal, reason\)/)
  assert.match(receiptPreview, /Cart override/)
  assert.match(receiptPreview, /sale\.cartPriceOverride\.adjustment/)
  assert.match(skumsSaleAdapter, /cart_price_override: sale\.cartPriceOverride/)
  assert.match(posOutbox, /cart_adjustment: sale\.cartPriceOverride\?\.adjustment \?\? 0/)
})

test('POS customer tagging supports unified search and manual customer add', () => {
  assert.match(customerBirthdayMigration, /add column if not exists birthday date/)
  assert.match(customersHook, /birthday\?: string/)
  assert.match(customersHook, /birthday\.eq/)
  assert.match(customersHook, /first_name\.ilike/)
  assert.match(customersHook, /phone\.ilike/)
  assert.match(customerModal, /Find or Add Customer/)
  assert.match(customerModal, /Search mobile, full name, email, birthday/)
  assert.match(customerModal, /Mobile number/)
  assert.match(customerModal, /Full name/)
  assert.match(customerModal, /Birthday/)
  assert.match(customerModal, /splitCustomerFullName/)
  assert.match(customerModal, /toPosCustomer/)
  assert.match(salePage, /<FranCustomerModal/)
  assert.match(salePage, /Fran member & rewards/)
})

test('Returns flow supports partial receipt returns instead of returning the full receipt by default', () => {
  assert.match(returnsPage, /Original receipt lines/)
  assert.match(returnsPage, /Choose only the wrong item and quantity being returned/)
  assert.match(returnsPage, /addReturnFromReceipt/)
  assert.match(returnsPage, /sourceReceiptNo/)
  assert.match(returnsPage, /originalQty/)
  assert.match(returnsPage, /originalLineRef/)
  assert.match(returnsPage, /skumsOriginalLineId/)
  assert.match(returnsPage, /Return item/)
  assert.match(returnsPage, /selected for return/)
  assert.doesNotMatch(returnsPage, /t\.items\.map\(\(it\) =>/)
})

test('POS store destinations and shelf locations use canonical codes', () => {
  assert.match(posMockData, /export interface StoreDestination/)
  assert.match(posMockData, /inventoryLocationId: 'fran-inv-orchard'/)
  assert.match(posMockData, /STORE_STORAGE_LOCATION_PATTERN/)
  assert.match(posMockData, /'SKN-1001': 'A01'/)
  assert.match(posMockData, /'TOL-5001': 'AA03'/)
  assert.match(posContext, /\$\{STORE\.code\}-/)
  assert.match(salePage, /storeLocationCodeFromMetadata/)
  assert.match(salePage, /storage_location_code/)
  assert.match(salePage, /Loc \{product\.storeLocationCode\}/)
  assert.match(transfersPage, /t\.toStoreCode === STORE\.code/)
  assert.match(transfersPage, /const TRANSFER_DESTINATIONS/)
  assert.match(transfersPage, /value=\{destCode\}/)
  assert.match(stockPage, /STORE_STORAGE_BUCKETS/)
  assert.match(stockPage, /Destination is locked to \{STORE\.name\}/)
  assert.match(stockPage, /Current POS store/)
  assert.match(stockPage, /IMS location/)
})

test('Stock inbound creates an IMS and SKUMS ready movement payload', () => {
  assert.match(stockMovement, /event: 'inventory\.stock_movement\.created'/)
  assert.match(stockMovement, /movement_type: 'inbound'/)
  assert.match(stockMovement, /inventory_location_id: store\.inventoryLocationId/)
  assert.match(stockMovement, /targets: \['inventory_management_system', 'skums'\]/)
  assert.match(stockPage, /createStockInboundPayload/)
  assert.match(stockPage, /supabase\s*\n\s*\.from\('products'\)\s*\n\s*\.update\(\{/)
  assert.match(stockPage, /inventory_count: payload\.balance_after/)
  assert.match(stockPage, /stock_movements:/)
  assert.match(stockPage, /inventory_management_system/)
  assert.match(stockPage, /notifyCatalogUpdated/)
})

test('POS can initiate damage, found stock, and transfer receipt inventory events', () => {
  assert.match(inventoryEventsMigration, /create table public\.pos_inventory_events/)
  assert.match(inventoryEventsMigration, /inventory\.damage\.reported/)
  assert.match(inventoryEventsMigration, /inventory\.found_stock\.reported/)
  assert.match(inventoryEventsMigration, /inventory\.transfer_receive\.reported/)
  assert.match(stockMovement, /createPosInventoryEventPayload/)
  assert.match(stockPage, /FLOOR_ACTIONS/)
  assert.match(stockPage, /inventory\.damage\.reported/)
  assert.match(stockPage, /inventory\.found_stock\.reported/)
  assert.match(stockPage, /createQueuedLocalInventoryEvent/)
  assert.match(stockPage, /updateLocalInventoryEvent/)
  assert.match(stockPage, /status: 'queued'/)
  assert.match(stockPage, /'sent'/)
  assert.match(stockPage, /'pending_approval'/)
  assert.match(stockPage, /createSkumsPosInventoryEvent/)
  assert.match(stockPage, /\.from\('pos_inventory_events'\)/)
  assert.match(stockPage, /Report floor event/)
  assert.match(transfersPage, /inventory\.transfer_receive\.reported/)
  assert.match(transfersPage, /createQueuedLocalTransferEvent/)
  assert.match(transfersPage, /updateLocalTransferEvent/)
  assert.match(transfersPage, /SKUMS \{transferSyncStatus\[selected\.ref\]\}/)
  assert.match(transfersPage, /createSkumsPosInventoryEvent/)
  assert.match(transfersPage, /\.from\('pos_inventory_events'\)/)
  assert.match(transfersPage, /idempotency_key: `\$\{STORE\.code\}-\$\{t\.ref\}-receive`/)
  assert.match(skumsClient, /\/api\/v1\/pos\/inventory-events/)
})

test('New users can create products manually or import from SKUMS', () => {
  assert.match(dashboardPage, /Choose your product source/)
  assert.match(dashboardPage, /\/products\?new=1/)
  assert.match(dashboardPage, /\/products\?import=skums/)
  assert.match(productsPage, /useSkumsImportJob/)
  assert.match(productsPage, /SkumsImportWizardContent/)
  assert.match(productsPage, /Create product manually/)
  assert.match(productsPage, /Import from SKUMS/)
  assert.match(productsHook, /export function useImportSkumsCatalog/)
  assert.match(productsHook, /loadSkumsConnectorForCompany/)
  assert.match(productsHook, /const pageSize = 250/)
  assert.match(productsHook, /const insertBatchSize = 100/)
  assert.match(productsHook, /listSkumsPosCatalog\(\{ limit: pageSize, offset \}, connector\)/)
  assert.match(productsHook, /while \(hasMore\)/)
  assert.match(productsHook, /typeof response\.next_offset === 'number'/)
  assert.match(productsHook, /response\.has_more \?\?/)
  assert.match(productsHook, /supabase\.from\('products'\)\.insert\(rows\.map/)
  assert.match(productsHook, /existingKeys\.add\(item\.sku\)/)
  assert.match(productsHook, /metadata: skumsMetadata\(item\)/)
  assert.match(productsHook, /storage_location_code: item\.storage_location_code/)
  assert.match(productsHook, /pos_catalog_updated/)
  assert.match(skumsConnectorHook, /useSaveSkumsConnector/)
})

test('POS main dashboard exposes operational tabs outside the register shell', () => {
  assert.match(dashboardPage, /type DashboardTab = 'overview' \| 'sales' \| 'analytics' \| 'users' \| 'customers' \| 'integrations'/)
  assert.match(dashboardPage, /label: 'Sales'/)
  assert.match(dashboardPage, /label: 'Analytics'/)
  assert.match(dashboardPage, /label: 'User Management'/)
  assert.match(dashboardPage, /label: 'Customers & Loyalty'/)
  assert.match(dashboardPage, /label: 'Integrations'/)
  assert.match(dashboardPage, /activeTab === 'sales'/)
  assert.match(dashboardPage, /activeTab === 'analytics'/)
  assert.match(dashboardPage, /activeTab === 'users'/)
  assert.match(dashboardPage, /activeTab === 'customers'/)
  assert.match(dashboardPage, /activeTab === 'integrations'/)
  assert.match(dashboardPage, /to="\/settings\/staff"/)
  assert.match(dashboardPage, /to="\/settings\/integrations"/)
  assert.match(dashboardPage, /to="\/customers"/)
  assert.match(dashboardPage, /Source Event Outbox/)
  assert.match(dashboardPage, /Reward redemption events/)
})

test('Products page supports filters and pagination', () => {
  assert.match(productsPage, /const \[statusFilter, setStatusFilter\]/)
  assert.match(productsPage, /const \[sourceFilter, setSourceFilter\]/)
  assert.match(productsPage, /const \[stockFilter, setStockFilter\]/)
  assert.match(productsPage, /const \[pageSize, setPageSize\]/)
  assert.match(productsPage, /Search by name, SKU, or barcode/)
  assert.match(productsPage, /All Status/)
  assert.match(productsPage, /All Sources/)
  assert.match(productsPage, /All Stock/)
  assert.match(productsPage, /10 \/ page/)
  assert.match(productsPage, /pageItems = filtered\.slice/)
  assert.match(productsPage, /Page \{safePage\.toLocaleString\(\)\} of \{totalPages\.toLocaleString\(\)\}/)
  assert.match(productsPage, /Previous/)
  assert.match(productsPage, /Next/)
  assert.match(productsPage, /productSource\(product\) === 'skums'/)
})

test('POS demo copy avoids banned vendor names while showing future hardware integrations', () => {
  const demoCopy = [posMockData, reportsPage, transfersPage].join('\n')
  const bannedVendorPattern = new RegExp(`${'S' + 'AP'}|${'Magent' + 'o'}`, 'i')
  assert.doesNotMatch(demoCopy, bannedVendorPattern)
  assert.match(posMockData, /Receipt printer/)
  assert.match(posMockData, /Barcode scanner/)
  assert.match(posMockData, /Payment terminal/)
  assert.match(posMockData, /Coming soon/)
  assert.match(reportsPage, /Future integrations/)
})

test('Split payment method reset is visually distinct from modal close', () => {
  assert.match(paymentModal, /Supports split payment with up to two tenders per sale/)
  assert.match(paymentModal, /ArrowLeft/)
  assert.match(paymentModal, /Change method/)
  assert.doesNotMatch(paymentModal, /<X className="h-4 w-4" \/>/)
})

test('Split payments are capped at two tenders and stored value suggestions respect balances', () => {
  assert.match(posMockData, /id: 'paynow', label: 'PayNow QR'/)
  assert.match(posMockData, /id: 'square_pos', label: 'Square POS'/)
  assert.match(paymentModal, /MAX_TENDERS_PER_PAYMENT = 2/)
  assert.match(paymentModal, /providerMetadata/)
  assert.match(paymentModal, /adapter: 'square_pos'/)
  assert.match(paymentModal, /Open Square POS/)
  assert.match(paymentModal, /const closeAndReset = \(\) =>/)
  assert.match(paymentModal, /payments\.length >= MAX_TENDERS_PER_PAYMENT/)
  assert.match(paymentModal, /Math\.min\(storeCreditAvail, Math\.max\(remaining, 0\)\)/)
  assert.match(paymentModal, /amountTooHigh/)
})
