import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const migration = readFileSync(new URL('../supabase/migrations/00011_create_pos_return_checks.sql', import.meta.url), 'utf8')
const sharedTypes = readFileSync(new URL('../packages/shared/src/types/database.ts', import.meta.url), 'utf8')
const eligibility = readFileSync(new URL('../dashboard/src/pos/lib/return-eligibility.ts', import.meta.url), 'utf8')
const returnsPage = readFileSync(new URL('../dashboard/src/pos/pages/returns.tsx', import.meta.url), 'utf8')
const outbox = readFileSync(new URL('../dashboard/src/pos/lib/pos-outbox.ts', import.meta.url), 'utf8')
const skumsAdapter = readFileSync(new URL('../dashboard/src/pos/lib/skums-sale-adapter.ts', import.meta.url), 'utf8')

test('POS return checks are durable and row-scoped by company', () => {
  assert.match(migration, /create table if not exists public\.pos_return_checks/)
  assert.match(migration, /crmos_decision_id text/)
  assert.match(migration, /crmos_authorization_id text/)
  assert.match(migration, /email_hint text not null/)
  assert.match(migration, /requested_action text not null check/)
  assert.match(migration, /decision text not null check/)
  assert.match(migration, /allowed_actions jsonb not null default '\[\]'::jsonb/)
  assert.match(migration, /raw_decision jsonb not null default '\{\}'::jsonb/)
  assert.match(migration, /alter table public\.pos_returns/)
  assert.match(migration, /add column if not exists return_check_id uuid references public\.pos_return_checks/)
  assert.match(migration, /alter table public\.pos_return_lines/)
  assert.match(migration, /add column if not exists match_type text not null default 'no_matched_sale'/)
  assert.match(migration, /revoke all on table public\.pos_return_checks from public/)
  assert.match(migration, /grant select, insert, update on table public\.pos_return_checks to authenticated, service_role/)
  assert.match(migration, /alter table public\.pos_return_checks enable row level security/)
  assert.match(migration, /company_id in \(select public\.get_user_company_ids\(\)\)/)
})

test('shared types expose the crmOS return eligibility contract', () => {
  assert.match(sharedTypes, /export type PosReturnRequestedAction = 'refund' \| 'exchange' \| 'store_credit' \| 'either'/)
  assert.match(sharedTypes, /export type PosReturnEligibilityDecision =/)
  assert.match(sharedTypes, /'store_credit_only'/)
  assert.match(sharedTypes, /export interface PosReturnCheck/)
  assert.match(sharedTypes, /crmos_decision_id: string \| null/)
  assert.match(sharedTypes, /export interface PosReturnEligibilityRequest/)
  assert.match(sharedTypes, /export interface PosReturnEligibilityResponse/)
  assert.match(sharedTypes, /crmos_return_eligibility\?: CrmosReturnEligibilitySettings \| null/)
})

test('POS eligibility helper checks product plus email and persists a return check', () => {
  assert.match(eligibility, /pendingReturnChecksStorageKey = 'pos_pending_return_checks'/)
  assert.match(eligibility, /customerEmail: string/)
  assert.match(eligibility, /product: Product/)
  assert.match(eligibility, /orderDateHint\?: string \| null/)
  assert.match(eligibility, /requestedAction: PosReturnRequestedAction/)
  assert.match(eligibility, /function findDemoPurchase/)
  assert.match(eligibility, /email_order_match/)
  assert.match(eligibility, /email_product_match_no_order/)
  assert.match(eligibility, /\.from\('pos_return_checks'\)/)
  assert.match(eligibility, /localReturnCheckId: persisted\.id/)
  assert.match(eligibility, /decisionAllowsReturn/)
})

test('returns page starts with crmOS eligibility and stamps approved lines', () => {
  assert.match(returnsPage, /Check return/)
  assert.match(returnsPage, /Customer email/)
  assert.match(returnsPage, /Order date/)
  assert.match(returnsPage, /Receipt\/order/)
  assert.match(returnsPage, /checkReturnEligibility/)
  assert.match(returnsPage, /Add approved return/)
  assert.match(returnsPage, /Add override return/)
  assert.match(returnsPage, /crmosDecisionId: eligibility\.decisionId/)
  assert.match(returnsPage, /crmosAuthorizationId: eligibility\.authorizationId/)
  assert.match(returnsPage, /crmosAllowedActions: eligibility\.allowedActions/)
  assert.match(returnsPage, /matchType: matched \? 'exact_order_line'/)
  assert.match(returnsPage, /authorizedReturnQty: approvedQty/)
  assert.match(returnsPage, /const maxReturnQty = l\.authorizedReturnQty \?\? l\.originalQty \?\? 99/)
  assert.match(returnsPage, /Admin override required/)
  assert.match(returnsPage, /ManagerAuthModal/)
  assert.match(returnsPage, /managerOverrideBy: eligibility\.managerRequired \? adminOverrideApprover : null/)
  assert.match(returnsPage, /updateAdminOverrideReason/)
  assert.match(returnsPage, /disabled=\{!canComplete\}/)
})

test('POS completion payloads carry crmOS authorization metadata', () => {
  assert.match(outbox, /crmosDecisionId/)
  assert.match(outbox, /crmosAuthorizationId/)
  assert.match(outbox, /crmos_order_line_id/)
  assert.match(outbox, /authorized_qty/)
  assert.match(outbox, /eligibility_reason_codes/)
  assert.match(outbox, /manager_override_by/)
  assert.match(outbox, /manager_overrides: managerOverrides/)
  assert.match(outbox, /decision_ids: crmosDecisionIds/)
  assert.match(outbox, /authorization_ids: crmosAuthorizationIds/)
  assert.match(skumsAdapter, /crmos_decision_id/)
  assert.match(skumsAdapter, /crmos_authorization_id/)
  assert.match(skumsAdapter, /authorized_return_qty/)
  assert.match(skumsAdapter, /manager_override_by/)
  assert.match(skumsAdapter, /match_type/)
})
